export const Images = [
  "./assets/images/photos/kayal.jpg",
  "./assets/images/photos/temple.jpg",
  "./assets/images/photos/sea_3.jpg",
  "./assets/images/photos/sea_2.jpg",
  "./assets/images/photos/sea.jpg",
  "./assets/images/photos/sea_1.jpg",
  "./assets/images/photos/flower_1.jpg",
  "./assets/images/photos/flower.jpg",
  "./assets/images/photos/light_house.jpg",
  "./assets/images/photos/lights.jpg",
  "./assets/images/photos/frnd.jpg",
  "./assets/images/photos/led.jpg",
  "./assets/images/photos/lamp.jpg",
  "./assets/images/photos/mall.jpg",
  "./assets/images/photos/lamp_1.jpg",
  // "./assets/images/photos/mac.jpg",
  //   "./assets/images/photos/night_light.jpg",
  // "./assets/images/photos/dry.jpg",
  "./assets/images/photos/work_station.jpg",
  "./assets/images/photos/work_station.jpg",
  "./assets/images/photos/work_station.jpg",
];
